### ISSUE TITLE
AutoSurround not working with curly braces inside a string with ReSharper

### ISSUE THREAD

**Issue by Patroklo** [reduckted/AutoSurround#5]
It seems there's a problem that affects only the curly braces on the c# editor (haven't checked on other languajes, sorry).

If I have a selected text inside a double quotation mark (a string), for example:

![image](https://user-images.githubusercontent.com/1254017/203502651-873b5179-8a19-4ac4-9ba7-748509f4c937.png)

I can use the Autosurround for parentheses, square brackets, angle brackets and double quotes without any problem, but for some reason, it fails with curly braces, deleting all the text and adding only the opening curly brace.

Working example with square bracket 
![image](https://user-images.githubusercontent.com/1254017/203503182-ede04f0b-7224-4332-9dcd-9fb806747e24.png)

What happens with curly braces
![image](https://user-images.githubusercontent.com/1254017/203503319-826c9b9d-10b9-4154-a811-bbd1bc73352f.png)

Right now I have Visual Studio Professional 2022 installed.

**Comment by Patroklo** [comment]
I'm an idiot, it seems that it has something to do with Resharper, I've thought that it could have something to do with that, and I disabled it, restarted visual studio and now the curly braces are working as expected... I'll close the Issue just to let other people with the same problem know. Now I'll have to find the exact configuration that is making this behaviour.

**Comment by Patroklo** [comment]
I've found the configuration problem, there's a "Braces and parentheses" behavior that suppossedly does the same as this package; unfortunally, at least for me, has never worked (in different computers and vs studio versions).

This configuration is working for me to prevent the curly braces problem:

They are on options -> editor -> behavior (from the Resharper options, of course).

Uncheck "Surround selection on typing a quuote, brace or parenthesis" and "Auto-insert pair brackets, parentheses and quotes"

Set "Auto-insert closing brace" to "None".

**Comment by reduckted** [comment]
Thanks for reporting this. I'll pin this issue in case anyone else encounters it.
