### ISSUE TITLE
Not working in .vbhtml files

### ISSUE THREAD

**Issue by graymatter00** [reduckted/AutoSurround#8]
AutoSourround doesn't seem to be working in .vbhtml files.  See video below.  All other file types I've trined seem to work as expected, including standard html files.

https://github.com/reduckted/AutoSurround/assets/7201626/2adef59a-f181-48e3-92a6-941d7ca723ea

![image](https://github.com/reduckted/AutoSurround/assets/7201626/f079c517-ac9a-4356-b5dc-bd4ab88d767b)

![image](https://github.com/reduckted/AutoSurround/assets/7201626/afaee689-89e0-47b0-bb6b-c37a1a108d40)

**Comment by reduckted** [comment]
Fixed in v1.5.0 (should be available in the marketplace shortly). I've used the same characters as `.cshtml` files, which are:
* `'`
* `"`
* `<`
